name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
        - cron: "30 18 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: 0xrishavsharma/0xrishavsharma@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
